M48
; DRILL file {KiCad 8.0.0-rc1} date 2025-12-23T23:51:38+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-12-23T23:51:38+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0-rc1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.7008Y-1.2205
X3.7008Y-3.4646
X9.685Y-1.2205
X9.685Y-3.4646
M30
